### ISSUE TITLE
Module doesn't compile

### ISSUE THREAD

**Issue by rpominov** [purescript-contrib/purescript-lists#26]
Run into it while going through https://github.com/paf31/purescript-book , on chapter3 I get this error:

```
$ grunt
Running "psc:all" (psc) task
>> Error creating file dist/Main.js
>> 
Warning: "bower_components/purescript-lists/src/Data/List.purs" (line 218, column 15):
unexpected '='
expecting no indentation or end of input Use --force to continue.
Error: "bower_components/purescript-lists/src/Data/List.purs" (line 218, column 15):
unexpected '='
expecting no indentation or end of input
    at callDone (/Users/anon/projects/other/purescript-book/chapter3/node_modules/grunt/node_modules/grunt-legacy-util/index.js:159:56)
    at ChildProcess.<anonymous> (/Users/anon/projects/other/purescript-book/chapter3/node_modules/grunt/node_modules/grunt-legacy-util/index.js:198:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)

Aborted due to warnings.
```

**Comment by paf31** [comment]
What compiler version are you using?

**Comment by rpominov** [comment]
`0.6.0` (from homebrew).

**Comment by rpominov** [comment]
Oh, sorry I was using version previously installed manually. It works great with `0.6.9.5` from homebrew.

Thanks! Sorry for bothering.
